### ISSUE TITLE
On OSx

### ISSUE THREAD

**Issue by epageperron** [cdli-gh/annotation_assistant#1]
```
epp-mtaac:~ emilie$ python3 --version
Python 3.6.2
epp-mtaac:~ emilie$ python3 main.py
Traceback (most recent call last):
  File "main.py", line 2, in <module>
    import htmlPy
  File "/usr/local/lib/python3.6/site-packages/htmlPy/__init__.py", line 4, in <module>
    from PySide.QtCore import QObject as Object
ModuleNotFoundError: No module named 'PySide'
epp-mtaac:~ emilie$ sudo -H pip3 install PySide
Collecting PySide
  Using cached https://files.pythonhosted.org/packages/36/ac/ca31db6f2225844d37a41b10615c3d371587677efd074db29855e7035de6/PySide-1.2.4.tar.gz
    Complete output from command python setup.py egg_info:
    only these python versions are supported: [(2, 6), (2, 7), (3, 2), (3, 3), (3, 4)]
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-install-_hs76k2p/PySide/
epp-mtaac:~ emilie$ 
```

**Comment by khoidt** [comment]
I see. There should be a PySide package for iOS & Python 3.6. I will find it and add to the dependencies folder.
