### ISSUE TITLE
login error

### ISSUE THREAD

**Issue by wangj619** [cdli-gh/annotation_assistant#2]
I was able to install everything, but when I tried to login, nothing happened. 
![error](https://user-images.githubusercontent.com/37027125/40241865-0f9d4bfc-5a8a-11e8-9266-33ffd887fa69.PNG)

**Comment by khoidt** [comment]
Hi @wangj619! I will look into this, it's not normal. Meanwhile, try the following quick fix:
1. Download [login_data.zip](https://github.com/cdli-gh/annotation_assistant/files/2020188/login_data.zip) to `annotation_assistant/scr/data/`.
2. Unzip it.
3. Open the JSON file in a plain text editor (e.g. Windows's native Notepad or Notepad++).
4. Add your Github password in the empty quotes (`"password": ""`).
5. Save the changes.

Then try to run it again and let me know if it works.

**Comment by epageperron** [comment]
@khoidt if you think it might useful, we can also have users pair an SSH key, it might be safer too? Just let me know if you want that, I can set it up for everyone.

**Comment by khoidt** [comment]
@epageperron I've made this a new issue, see #3.

**Comment by epageperron** [comment]
I just tried running the tool under Linux and I get a similar problem, I enter login and password, nothing happens in the GUI and I get the following error message in the console : 
```
epp@waga-masta:/alty/data/annotation_assistant/scr$ python3.6 main.py
check github login data
Collecting git+https://github.com/cdli-gh/morphology-pre-annotation-tool.git
  Cloning https://github.com/cdli-gh/morphology-pre-annotation-tool.git to /tmp/pip-req-build-aAsuvw
Requirement not upgraded as not directly required: click in /home/epp/.linuxbrew/lib/python2.7/site-packages (from cdlimpatool==0.5.7) (6.7)
Building wheels for collected packages: cdlimpatool
  Running setup.py bdist_wheel for cdlimpatool: started
  Running setup.py bdist_wheel for cdlimpatool: finished with status 'done'
  Stored in directory: /tmp/pip-ephem-wheel-cache-rzrIi0/wheels/1c/5d/2f/94143d5930f82b8def20ed1a46642b1771b52080e7798448a1
Successfully built cdlimpatool
Installing collected packages: cdlimpatool
  Found existing installation: cdlimpatool 0.5.7
    Uninstalling cdlimpatool-0.5.7:
      Successfully uninstalled cdlimpatool-0.5.7
Successfully installed cdlimpatool-0.5.7

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "/usr/local/lib/python3.6/site-packages/eel/__init__.py", line 184, in _process_message
    return_val = _exposed_functions[message['name']](*message['args'])
  File "main.py", line 407, in github_login
    d.github_login(json_data)
  File "main.py", line 340, in github_login
    self.plug_annotation_backend()
  File "main.py", line 349, in plug_annotation_backend
    self.login_data["password"])
  File "main.py", line 111, in __init__
    self.actualize()
  File "main.py", line 120, in actualize
    self.clone_annotated()
  File "main.py", line 144, in clone_annotated
    cwd=self.ANNOTATED_ROOT)
  File "main.py", line 73, in run
    startupinfo=self.hide_console())
  File "/usr/local/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/alty/data/annotation_assistant/scr/data': '/alty/data/annotation_assistant/scr/data'
2018-05-29T20:02:26Z <Greenlet "Greenlet-0" at 0x7f659d9b3d48: _process_message({'call': 1.1783228169501139, 'name': 'github_login, <geventwebsocket.websocket.WebSocket object at 0x7)> failed with FileNotFoundError


```

**Comment by khoidt** [comment]
Should be fixed now. The problem was in the gitignored data directory. The latest fix creates it when it is missing.
